name: Build and publish the latest image to Docker Hub

on:
  push:
    branches:
      - main
    paths-ignore:
      - .editorconfig
      - .gitignore
  workflow_dispatch:

jobs:
  publish-latest:
    runs-on: ubuntu-20.04
    name: Build and publish the latest image to Docker Hub
    steps:

      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push the image to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/grcov:latest

      - name: Print the image's digest
        run: echo ${{ steps.docker_build.outputs.digest }}
